<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;700&display=swap" />
    <link rel="stylesheet" href="css/login-style.css">
  </head>
  <body>
    <div class="main-container">
      <div class="flex-column-b">
        <div class="container"></div>
        <div class="rectangle"><div class="container-1"></div></div>
      </div>
      <div class="flex-column-aab">
        <div class="frame">
          <div class="cuplikan-layar"></div>
          <span class="mark-up">MARK-UP</span>
        </div>
        <div class="container-2">
          <div class="heading">
            <span class="welcome-back">Welcome Back</span>
          </div>
          <div class="paragraph">
            <span class="enter-details"
              >Welcome Back, Please enter Your details</span
            >
          </div>
        </div>
        <div class="container-3">
          <div class="button"><span class="sign-in">Sign In</span></div>
          <div class="signup"><span class="container-4">Signup</span></div>
        </div>
        <div class="group-3">
          <div class="label">
            <span class="email-address">Email Address</span>
          </div>
          <div class="container-5">
            <div class="email-input">
              <span class="email">iailrezamp@gmail.com</span>
            </div>
            <div class="container-6"><div class="icon"></div></div>
            <div class="container-7"><div class="icon-8"></div></div>
          </div>
        </div>
        <div class="container-9">
          <div class="label-a"><span class="password">Password </span></div>
          <div class="container-b">
            <div class="email-input-c">
              <span class="hidden-text">********</span>
            </div>
            <div class="container-d"><div class="icon-e"></div></div>
            <div class="container-f"><div class="lock-icon"></div></div>
          </div>
        </div>
        <div class="button-10"><span class="continue">Continue</span></div>
        <span class="or-continue-with">Or Continue With</span>
        <div class="container-11">
          <div class="button-12"><div class="icon-13"></div></div>
          <div class="button-14"><div class="icon-15"></div></div>
          <div class="button-16"><div class="icon-17"></div></div>
        </div>
      </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
